[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/login-taller.html"
  status = 301
  force = true

[[redirects]]
  from = "/logout-taller.html"
  to = "/login-taller.html"
  status = 301
  force = true
